//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHWD.DataTranslate.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class dev_info
    {
        public int ID { get; set; }
        public string DEV_NAME { get; set; }
        public string VER { get; set; }
        public string IP { get; set; }
        public string MASK { get; set; }
        public string GATEWAY { get; set; }
        public string STATE { get; set; }
        public string LAST { get; set; }
    }
}
