//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHWD.DataTranslate.DataProvider
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class data_centerEntities : DbContext
    {
        public data_centerEntities()
            : base("name=data_centerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dev_info> dev_info { get; set; }
        public virtual DbSet<sensor_data_hour> sensor_data_hour { get; set; }
        public virtual DbSet<sensor_data_min> sensor_data_min { get; set; }
    }
}
