//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHWD.DataTranslate.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class sensor_data_min
    {
        public int ID { get; set; }
        public string StatCode { get; set; }
        public float TP { get; set; }
        public float DB { get; set; }
        public System.DateTime DataTime { get; set; }
        public float WindSpeed { get; set; }
        public float Rain { get; set; }
        public float WindDirection { get; set; }
        public float Temperature { get; set; }
        public float Humidity { get; set; }
        public float AirPressure { get; set; }
        public float AirIon { get; set; }
        public string DataStatus { get; set; }
    }
}
